version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=host.docker.internal,1433;Database=JobLess;User Id=sa;Password=LocalhostPa55!;
    depends_on:
      - db # Ensures the backend waits for the database to be ready

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend  # Frontend waits for the backend to be up first

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=LocalhostPa55!
    ports:
      - "1433:1433" # Exposing SQL Server port 1433 to be accessible
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
