version: "3.9"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    networks:
      - mynetwork
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=JobLess;User Id=sa;Password=YourStrong!Passw0rd;Encrypt=False;TrustServerCertificate=True;"
    ports:
      - "5000:5000"
    depends_on:
      - mssql
    networks:
      - mynetwork
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - mynetwork
    restart: unless-stopped

volumes:
  mssqldata:

networks:
  mynetwork:
    driver: bridge
